name: hackathon-hacks-ai-2023

services:
  api-service:
    #build:
    #  context: .
    image: airndlab/hackathon-hacks-ai-2023-api-service
    environment:
      - RANKER_SERVICE_URL=http://ranker-service:80
    ports:
      - 8080:80
    networks:
      - service-net
    depends_on:
      - ranker-service

  ranker-service:
    image: airndlab/hackathon-hacks-ai-2023-ranker-service
    environment:
      - DIR_PATH=/myfiles
    volumes:
      - ./demo/myfiles:/myfiles
    ports:
      - 8081:80
    networks:
      - service-net

networks:
  service-net:
    driver: bridge
